/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AuthenticationRequest {
  email?: string;
  /**
   * @minLength 8
   * @maxLength 255
   */
  password?: string;
}
