/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FilterRestaurantsParams = {
name?: string;
tag?: string;
city?: string;
vegetarian?: boolean;
vegan?: boolean;
averageRating?: number;
totalReviewsCount?: number;
latitude?: number;
longitude?: number;
radius?: number;
page?: number;
size?: number;
};
