/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './addLikeToRestaurantParams';
export * from './addPreferencesForUserParams';
export * from './authenticationRequest';
export * from './authenticationResponse';
export * from './filterRestaurantsParams';
export * from './filterRestaurantsWithScoresParams';
export * from './getAllRestaurantsParams';
export * from './getPreferencesByUserIdParams';
export * from './getRestaurantsByTagParams';
export * from './grantedAuthority';
export * from './increasePreferenceCountParams';
export * from './listOfPreferencesDTO';
export * from './pageRestaurant';
export * from './pageableObject';
export * from './preference';
export * from './preferenceDTO';
export * from './preferenceDTOPreferenceType';
export * from './preferencePreferenceType';
export * from './register200';
export * from './registerRequest';
export * from './removeLikeFromRestaurantParams';
export * from './restaurant';
export * from './sortObject';
export * from './tag';
export * from './tagName';
export * from './user';
export * from './userRole';