/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PreferenceDTOPreferenceType } from './preferenceDTOPreferenceType';

export interface PreferenceDTO {
  count?: number;
  preferenceType?: PreferenceDTOPreferenceType;
}
