/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PreferencePreferenceType } from './preferencePreferenceType';

export interface Preference {
  count?: number;
  id?: number;
  preferenceType?: PreferencePreferenceType;
}
