/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PreferenceDTOPreferenceType = typeof PreferenceDTOPreferenceType[keyof typeof PreferenceDTOPreferenceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferenceDTOPreferenceType = {
  TURCESC: 'TURCESC',
  INDIAN: 'INDIAN',
  ITALIENESC: 'ITALIENESC',
  LIBANEZ: 'LIBANEZ',
  TRADITIONAL_ROMANESC: 'TRADITIONAL_ROMANESC',
  FAST_FOOD: 'FAST_FOOD',
  SEA_ORIENTED: 'SEA_ORIENTED',
} as const;
