/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  email?: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  lastName: string;
  /**
   * @minLength 8
   * @maxLength 255
   */
  password?: string;
}
