/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Tag } from './tag';

export interface Restaurant {
  address?: string;
  averageRating?: number;
  city?: string;
  country?: string;
  id?: number;
  latitude?: number;
  longitude?: number;
  name?: string;
  openHours?: string;
  province?: string;
  recommendationScore?: number;
  region?: string;
  restaurantLink?: string;
  tags?: Tag[];
  totalReviewsCount?: number;
  usersLikes?: number;
  vegan?: boolean;
  vegetarian?: boolean;
}
