/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AddLikeToRestaurantParams,
  AddPreferencesForUserParams,
  AuthenticationRequest,
  AuthenticationResponse,
  FilterRestaurantsParams,
  FilterRestaurantsWithScoresParams,
  GetAllRestaurantsParams,
  GetPreferencesByUserIdParams,
  GetRestaurantsByTagParams,
  IncreasePreferenceCountParams,
  ListOfPreferencesDTO,
  PageRestaurant,
  PreferenceDTO,
  Register200,
  RegisterRequest,
  RemoveLikeFromRestaurantParams
} from './model'
import { customInstance } from '../security/axiosConfig';



type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  export const addLikeToRestaurant = (
    params: AddLikeToRestaurantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/likeRestaurant`, method: 'POST',
        params
    },
      options);
    }
  
export const removeLikeFromRestaurant = (
    params: RemoveLikeFromRestaurantParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/dislikeRestaurant`, method: 'POST',
        params
    },
      options);
    }
  
export const increasePreferenceCount = (
    params: IncreasePreferenceCountParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `http://192.168.0.102:8080/api/v1/preference/increasePreferenceCountForUser`, method: 'POST',
        params
    },
      options);
    }
  
export const addPreferencesForUser = (
    listOfPreferencesDTO: ListOfPreferencesDTO,
    params: AddPreferencesForUserParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `http://192.168.0.102:8080/api/v1/preference/addPreferenceForUser`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listOfPreferencesDTO,
        params
    },
      options);
    }
  
export const register = (
    registerRequest: RegisterRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Register200>(
      {url: `http://192.168.0.102:8080/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest
    },
      options);
    }
  
export const authenticate = (
    authenticationRequest: AuthenticationRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AuthenticationResponse>(
      {url: `http://192.168.0.102:8080/api/v1/auth/authenticate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationRequest
    },
      options);
    }
  
export const getRestaurantsByTag = (
    params: GetRestaurantsByTagParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PageRestaurant>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/getByTag`, method: 'GET',
        params
    },
      options);
    }
  
export const getAllRestaurants = (
    params?: GetAllRestaurantsParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PageRestaurant>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/getAll`, method: 'GET',
        params
    },
      options);
    }
  
export const filterRestaurants = (
    params?: FilterRestaurantsParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PageRestaurant>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/filter`, method: 'GET',
        params
    },
      options);
    }
  
export const filterRestaurantsWithScores = (
    params?: FilterRestaurantsWithScoresParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PageRestaurant>(
      {url: `http://192.168.0.102:8080/api/v1/restaurants/filterWithScores`, method: 'GET',
        params
    },
      options);
    }
  
export const getPreferencesByUserId = (
    params: GetPreferencesByUserIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PreferenceDTO[]>(
      {url: `http://192.168.0.102:8080/api/v1/preference/getPreferencesByUserId`, method: 'GET',
        params
    },
      options);
    }
  
export const getAllPreferences = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string[]>(
      {url: `http://192.168.0.102:8080/api/v1/preference/getAllPreferences`, method: 'GET'
    },
      options);
    }
  
export type AddLikeToRestaurantResult = NonNullable<Awaited<ReturnType<typeof addLikeToRestaurant>>>
export type RemoveLikeFromRestaurantResult = NonNullable<Awaited<ReturnType<typeof removeLikeFromRestaurant>>>
export type IncreasePreferenceCountResult = NonNullable<Awaited<ReturnType<typeof increasePreferenceCount>>>
export type AddPreferencesForUserResult = NonNullable<Awaited<ReturnType<typeof addPreferencesForUser>>>
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type AuthenticateResult = NonNullable<Awaited<ReturnType<typeof authenticate>>>
export type GetRestaurantsByTagResult = NonNullable<Awaited<ReturnType<typeof getRestaurantsByTag>>>
export type GetAllRestaurantsResult = NonNullable<Awaited<ReturnType<typeof getAllRestaurants>>>
export type FilterRestaurantsResult = NonNullable<Awaited<ReturnType<typeof filterRestaurants>>>
export type FilterRestaurantsWithScoresResult = NonNullable<Awaited<ReturnType<typeof filterRestaurantsWithScores>>>
export type GetPreferencesByUserIdResult = NonNullable<Awaited<ReturnType<typeof getPreferencesByUserId>>>
export type GetAllPreferencesResult = NonNullable<Awaited<ReturnType<typeof getAllPreferences>>>
