/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AuthenticationRequest,
  AuthenticationResponse,
  Register200,
  RegisterRequest
} from './model'
import { customInstance } from '../security/axiosConfig';



type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  export const register = (
    registerRequest: RegisterRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Register200>(
      {url: `http://localhost:8080/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest
    },
      options);
    }
  
export const authenticate = (
    authenticationRequest: AuthenticationRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AuthenticationResponse>(
      {url: `http://localhost:8080/api/v1/auth/authenticate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationRequest
    },
      options);
    }
  
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type AuthenticateResult = NonNullable<Awaited<ReturnType<typeof authenticate>>>
